=== 2slow/ws-soap-server/data/schemaComments.xsd
<?xml version="1.0" encoding="ISO-8859-1"?> 
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="commentType">  
		<xs:sequence> 
			<xs:element name="author" type="xs:string"/> 
			<xs:element name="mark" type="mark"/>
			<xs:element name="text" type="xs:string"/>  
		</xs:sequence>
		<xs:attribute name="idParent" type="xs:int" use="required"/> 
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>

	<xs:simpleType name="mark"> 
		<xs:restriction base="xs:int"> 
			<xs:minInclusive value="0"/> 
			<xs:maxInclusive value="10"/> 
		</xs:restriction> 
	</xs:simpleType>

	<xs:element name="comments">
		<xs:complexType>
			<xs:sequence> 
				<xs:element name="comment" type="commentType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType> 
	</xs:element>
</xs:schema>

=== 2slow/ws-soap-server/data/comments.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<comments xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schemaComments.xsd">
  <comment idParent="1641">
    <author>rhannequin</author>
    <mark>4</mark>
    <text>not terrible</text>
  </comment>
  <comment idParent="1641">
    <author>2slow</author>
    <mark>8</mark>
    <text>good</text>
  </comment>
  <comment idParent="1641">
    <author>jagbomb</author>
    <mark>9</mark>
    <text>very good</text>
  </comment>
</comments>
